name: WireViz Diagram Automation

on:
  push:
    paths:
      - '**/*.wires.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
      - name: Install WireViz
        run: pip install wireviz
      - name: Generate Diagrams and Commit
        run: |
          set -e  # Ensure that the script exits on the first error
          
          # Initialize an empty array for ignore patterns
          ignore_patterns=()
          
          # Check if .wireviz-ignore exists and read it into the array if it does
          if [ -f ".wireviz-ignore" ]; then
            IFS=$'\n' read -d '' -r -a ignore_patterns < .wireviz-ignore
          fi
          
          # Find all .wires.yaml files and loop through them
          find . -name '*.wires.yaml' | while read file; do
            # Check each file against ignore patterns
            ignore=false
            for pattern in "${ignore_patterns[@]}"; do
              if [[ "$file" == $pattern ]]; then
                ignore=true
                break
              fi
            done
            
            if [ "$ignore" = false ]; then
              if ! wireviz "$file"; then
                echo "::error ::Failed to generate diagram for $file"
                exit 1
              fi
            else
              echo "Ignoring file $file based on .wireviz-ignore"
            fi
          done
          
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generated diagrams [skip ci]" && git push)
        shell: bash
