name: WireViz diagram automation

on:
  push:
    paths:
      - '**/*.wires.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
      - name: Install WireViz
        run: pip install wireviz
      - name: Generate Diagrams and Commit
        run: |
          set -e  # Ensure that the script exits on the first error
          git fetch --depth=1 origin main
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main) | grep '\.wires\.yaml$')
          echo "Changed .wires.yaml files: $CHANGED_FILES"
          for file in $CHANGED_FILES; do
            if [[ "$file" != *".github/"* ]]; then
              if ! wireviz "$file"; then
                echo "::error ::Failed to generate diagram for $file"
                exit 1
              fi
            fi
          done
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generated diagrams [skip ci]" && git push)
        shell: bash
